encoding: UTF-8
lang: en
permalink: /:year/:month/:day/:title/
future: true

pygments: true

sass:
  style: compressed

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  toc_levels: 1..3
  syntax_highlighter_opts:
    block:
      line_numbers: true

url: https://hgnulb.github.io
baseurl: /blog
title: 走在修行的大街上
description: "小兵的BLOG"
keywords: "programmer,full stack engineer,java,golang,python,走在修行的大街上,程序员,全栈工程师"
motto: "选择比努力更重要，观念比选择更重要。"
author:
  name: HGNULB
  job_title: 后端开发工程师
  profile: A blog that you won't read
  email: hgnulb@163.com
  social_links:
    - name: leetcode
      url: https://leetcode.cn/u/hgnulb/
      enabled: true
    - name: github
      url: https://github.com/hgnulb/
      enabled: true
    - name: douban
      url: https://book.douban.com/people/257597606/
      enabled: true
    - name: stackoverflow
      url: https://stackoverflow.com/users/10383025/
      enabled: true
    - name: nowcoder
      url: https://www.nowcoder.com/profile/8667211/
      enabled: true

paths:
  blog: /home/
  categories: /categories/
  tags: /tags/

exclude:
  - README.md
  - CNAME

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

busuanzi:
  enabled: true

  site_uv: true
  site_uv_header: 本站总访客数
  site_uv_footer: 人

  site_pv: true
  site_pv_header: 本站总访问量
  site_pv_footer: 次

  page_pv: true
  page_pv_header: 本文总阅读量
  page_pv_footer: 次

cdn:
  jsdelivr:
    enabled: false
    gh-pages: https://cdn.jsdelivr.net/gh/hgnulb/blog@gh-pages
  jquery:
    version: 3.6.1
  popper-js:
    version: 2.11.6
  typed-js:
    version: 2.0.12
  lazyload:
    enabled: true
    version: 1.9.1
  simple-jekyll-search:
    version: 1.9.2
  modernizr:
    version: 2.8.3
  pace:
    version: 1.2.4
  tippy-js:
    version: 6.3.7
    themes:
      - translucent
      - light-border
      - light
      - material
